spring.application.name=Sonshine_Inventory
spring.datasource.url=jdbc:mysql://localhost:3306/sonshine_inventory
spring.datasource.username=sonshine
spring.datasource.password=sonshine
server.address=0.0.0.0