spring.application.name=Sonshine_Inventory
spring.datasource.url=jdbc:mysql://localhost:3306/sonshine_inventory
spring.datasource.username=sonshine
spring.datasource.password=sonshine
server.address=0.0.0.0
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

server.port=${SERVER_PORT:8080}
server.ssl.enabled=${SSL_ENABLED:false}
server.ssl.key-store=${SSL_KEY_STORE:}
server.ssl.key-store-password=${SSL_KEY_STORE_PASSWORD:}
server.ssl.key-store-type=${SSL_KEY_STORE_TYPE:PKCS12}
server.ssl.key-alias=${SSL_KEY_ALIAS:}